name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: [Windows-latest]

steps:
  - name: Echo         # nome amigável para este passo
    run: echo "Hello, world!"  

