name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: [ self-hosted, Windows ]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Restore dependencies
        run: dotnet restore ${{ github.workspace }} --runtime ${{ vars.runtime }} --no-cache

