name: CI: Build, Test & Publish (.NET 9)

# dispara em push e pull request na branch main
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-test-publish:
    # você pode usar 'windows-latest' ou o seu self-hosted se preferir
    runs-on: windows-latest

    strategy:
      # matrix pra expandir pra multiplos RIDs, se necessário
      matrix:
        runtime: ["win-x64"]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup .NET 9 SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "9.0.x"

      - name: Restore dependencies
        run: dotnet restore --runtime ${{ matrix.runtime }} --no-cache

      - name: Build solution
        run: dotnet build --configuration Release --no-restore

      - name: Run unit tests
        run: dotnet test --configuration Release --no-build --verbosity normal

      - name: Publish self-contained app
        run: |
          dotnet publish \
            --configuration Release \
            --runtime ${{ matrix.runtime }} \
            --self-contained true \
            --output ./publish

      - name: Upload published artifact
        uses: actions/upload-artifact@v4
        with:
          name: published-app
          path: ./publish
